### ISSUE TITLE
Cross Compilation and Newer Versions of NW.JS

### ISSUE THREAD

**Issue by medemi68** [LeonardLaszlo/nw.js-armv7-binaries#28]
Hello,

First and foremost, I just want to say, you are amazing! Thank you for creating this project! I needed a version of NWjs for ARMv7 for a very complicated application, and this is exactly what I needed!

My only questions are whether or not it is possible to cross-compile nw.js using the build script you gave or does it have to be run on an ARMv7 chip? Also, does this work with newer versions of NW.JS? Such as 0.35?

Any help would be greatly appreciated, and thank you for the massive help already!

**Comment by LeonardLaszlo** [comment]
Hi, thank you! This is a cross-compilation guide. There is no way you will find an ARM device with enough RAM to built NW.js :D Since v.0.28.x there are some issues with the building process, which I could not fix yet because I am a bit busy lately. If you think you have time to take a look and perhaps try to build a newer version your contributions to this project are always welcome! :)

**Comment by LeonardLaszlo** [comment]
I released some newer versions btw.
