### ISSUE TITLE
nwjs 0.47.1 has been released

### ISSUE THREAD

**Issue by pleasantone** [LeonardLaszlo/nw.js-armv7-binaries#38]
Any chance we could get arm7l binaries (armhf) for the Pi?

**Comment by LeonardLaszlo** [comment]
Nope.

**Comment by pleasantone** [comment]
That was a bit terse. I’m curious, is there an issue I should be aware of with 0.47.1 and therefore I should not waste time trying to do it myself, or do you just not want to do it? I’m really new to nwjs so I’m asking out of ignorance, not trying to be disagreeable.

**Comment by LeonardLaszlo** [comment]
I've built NW.js for ARM when I was a student, because I wanted to run an app on my Odroid.
There was no tutorial at that time and I've mostly asked the help of other people, because I was and I am still clueless about the building process.

Now, 5 years later, people are expecting me to deliver every version they need, although now there is a documentation in this repo for it and anybody can do it themselves. What bothers me is that nobody is asking kindly, but rather it sounds like a demand.

Building 1 version takes more than 24 hours on my laptop. It's not that I don't want to do it, I just have a personal life to live and this is not my priority now. I am doing all this on a best effort basis.

I will gladly add other maintainers to this repo is anyone offers to make the build himself. So far nobody volunteered.

**Comment by LeonardLaszlo** [comment]
I've opened an issue for that now: 
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/issues/39

**Comment by pleasantone** [comment]
Ok thanks for the explanation! You were updating the repo and doing old releases so I had no clue about the context.

Of course we can build our own, just considered you a central repository.

Thanks for your work!!!

**Comment by LeonardLaszlo** [comment]
I am running the build of the latest version now. I think it will take few more hours to finish.

**Comment by pleasantone** [comment]
Wow, thank you!!! You’re awesome!
